#!/usr/bin/env bash

TAG=${TAG:-"rules-engine"}
REGISTRY=${REGISTRY:-"gcf-artifacts"}
REGION=${REGION:-""}
PROJECT=${PROJECT:-""}

while [ $# -gt 0 ]; do

   if [[ $1 == *"--"* ]]; then
        PARAM="${1/--/}"
        PARAM="$(echo $PARAM | tr 'a-z' 'A-Z')"
        declare $PARAM="$2"
   fi

  shift
done

echo "[ $(date +%T) ] Beginning container push ..."

[[ -z $REGION ]] && { echo "Parameter --region cannot be empty"; exit 1;}
[[ -z $PROJECT ]] && { echo "Parameter --project cannot be empty"; exit 1;}

docker push "$REGION-docker.pkg.dev/$PROJECT/$REGISTRY/$TAG"

echo "[ $(date +%T) ] Completed container push..."